# config/packages/messenger.yaml

framework:
    messenger:
        transports:
            logs_ingest:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: logs.ingest
                        type: direct
                    queues:
                        logs.ingest:
                            binding_keys: [ logs.ingest ]
                            arguments:
                                x-max-priority: '7'

        routing:
            App\Message\LogIngestMessage: logs_ingest

when@test:
    framework:
        messenger:
            transports:
                logs_ingest: 'in-memory://'
